client_id = 'CLIENT_ID'
client_secret = 'CLIENT_SECRET'
username = 'USERNAME' 
password = 'PASSWORD'
user_agent = 'USER_AGENT'
subreddit_name = 'SUBREDDIT_NAME'
trigger = 'TRIGGER'
path_to_quotes = './quotes.txt'
